#!/usr/bin/env python3

import socket
import sys

HOST = sys.argv[1]
PORT = int(sys.argv[2])
ADDR = (HOST, PORT)

def connect():
    #connect to server
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.connect(ADDR)
        #recv inital message from server
        msg = s.recv(1024)
        #decode message
        msg = msg.decode()
        # inilize counter
        count = 0
        # start while loop

        while msg == 'Pick a number from 0-25\n':
            # conver conter to a str
            str_count = f'{count}\n'
            # encode str
            en_count = str_count.encode()
            # send encoded counter to server
            s.send(en_count)
            # increment counter
            count += 1
            # listening for server responce and reaasing msg variable
            msg = s.recv(1024)
            msg = msg.decode()

    #print message ffrom server
    print(msg.strip())
    #for debugging
    #print(count)


connect()
