#!/usr/bin/env python3

import socket
import sys

HOST = sys.argv[1]
PORT = int(sys.argv[2])
ADDR = (HOST, PORT)

with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
     s.connect(ADDR)

     message = 'Hello\n'
     message = message.encode()

     #s.send(message)

     # to receive add this to a while loop
     msg = s.recv(1024)
     print(msg.decode())
